import { Product } from './index';

export const data: Product[] = [
  {
    name: 'Cuaderno',
    category: 'Papeleria',
    purchase_price: 1500,
	  sale_price: 2500,
    amount: 5,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapiz',
    category: 'Papeleria',
    purchase_price: 800,
	  sale_price: 1200,
    amount: 10,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapicero',
    category: 'Papeleria',
    purchase_price: 15000,
	  sale_price: 25500,
    amount: 25,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapicero',
    category: 'Papeleria',
    purchase_price: 15000,
	  sale_price: 25500,
    amount: 25,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapicero',
    category: 'Papeleria',
    purchase_price: 15000,
	  sale_price: 25500,
    amount: 25,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapicero',
    category: 'Papeleria',
    purchase_price: 15000,
	  sale_price: 25500,
    amount: 25,
	  brand: 'Faber castell',
  },
  {
    name: 'Cuaderno',
    category: 'Papeleria',
    purchase_price: 1500,
	  sale_price: 2500,
    amount: 5,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapiz',
    category: 'Papeleria',
    purchase_price: 800,
	  sale_price: 1200,
    amount: 10,
	  brand: 'Faber castell',
  },
  {
    name: 'Cuaderno',
    category: 'Papeleria',
    purchase_price: 1500,
	  sale_price: 2500,
    amount: 5,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapiz',
    category: 'Papeleria',
    purchase_price: 800,
	  sale_price: 1200,
    amount: 10,
	  brand: 'Faber castell',
  },
  {
    name: 'Cuaderno',
    category: 'Papeleria',
    purchase_price: 1500,
	  sale_price: 2500,
    amount: 5,
	  brand: 'Faber castell',
  },
  {
    name: 'Lapiz',
    category: 'Papeleria',
    purchase_price: 800,
	  sale_price: 1200,
    amount: 10,
	  brand: 'Faber castell',
  },
];

//50 us states array
export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
  'Puerto Rico',
];
